
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x6d8980"
blue = "0x077b8b"
cyan = "0x46b0a4"
green = "0x2b8c69"
magenta = "0x888ba5"
red = "0xd26939"
white = "0xd3ebe9"
yellow = "0xbba622"

[colors.normal]
black = "0x0a0f14"
blue = "0x195465"
cyan = "0x63d8ca"
green = "0x26a98b"
magenta = "0x4e5165"
red = "0xc33027"
white = "0x98d1ce"
yellow = "0xedb54b"

[colors.primary]
background = "0x0a0f14"
foreground = "0x98d1ce"

[font]
size = 10

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code,Fira Code"
style = "SemiBold"

[font.italic]
family = "Fira Code,Fira Code"
style = "Retina"

[font.normal]
family = "Fira Code"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

[terminal]
