name: R0nin
accent: '#268bd2'
cursor: '#98d1ce'
background: '#0a0f14'
details: darker
foreground: '#98d1ce'

############################################################### SEE BELOW
#background_image:
#  # the path is relative to ~/.warp/themes/
#  # the full path to the picture is: ~/.warp/themes/warp.jpg
#  path: warp.jpg
#  # the opacity value is required and can range from 0-100
#  opacity: 60
############################################################### SEE ABOVE

terminal_colors:
  bright:
    black: '#6d8980'
    blue: '#077b8b'
    cyan: '#46b0a4'
    green: '#2b8c69'
    magenta: '#888ba5'
    red: '#d26939'
    white: '#d3ebe9'
    yellow: '#bba622'
  normal:
    black: '#0a0f14'
    blue: '#195465'
    cyan: '#63d8ca'
    green: '#26a98b'
    magenta: '#4e5165'
    red: '#c33027'
    white: '#98d1ce'
    yellow: '#edb54b'