---
"pane_group:navigate_next": none
"input:open_completion_suggestions": tab
"terminal:clear_blocks": none
"editor_view:move_to_line_start": ctrl-a
"pane_group:navigate_down": none
"editor:find": none
"notebookview:focus_terminal_input": none
"terminal:scroll_to_bottom_of_selected_block": none
"suggested_plan:refine": none
"editor_view:cut_all_right": none
"workspace:toggle_files_palette": none
"inline_ai_view:refine": none
"pane_group:add_up": ctrl-alt-up
"pane_group:close_current_session": ctrl-w
"workspace:move_tab_right": none
"editor_view:move_to_and_select_buffer_end": ctrl-shift-end
"terminal:toggle_block_filter_on_selected_or_last_block": none
"terminal:expand_block_selection_below": none
"workspace:move_tab_left": none
"workspace:view_changelog": none
"code_view:save": none
"terminal:toggle_teams_modal": none
"input:toggle_active_conversation_menu": none
"terminal:select_all_blocks": none
"editor_view:strikethrough": none
"input:enable_auto_detection": none
"terminal:scroll_to_top_of_selected_block": none
"requested_command:edit": none
"editor:edit_link": none
"editor_view:cut_word_left": none
"workspace:shift_focus_left": none
"terminal:find": none
"workspace:jump_to_latest_toast": none
"terminal:toggle_autoexecute_mode": none
"terminal:open_inline_ai": ctrl-shift-I
"pane_group:navigate_left": none
"pane_group:navigate_up": none
"terminal:bookmark_selected_block": none
"editor_view:move_to_line_end": ctrl-e
"pane_group:add_right": ctrl-alt-right
"input:clear_and_reset_ai_context_menu_query": none
"terminal:copy": none
Close Workflow: ctrl-shift-W
"workspace:toggle_warp_drive": none
"terminal:share_current_session": none
"terminal:copy_outputs": none
"terminal:expand_block_selection_above": none
"editor_view:underline": none
"workspace:disable_terminal_input_syncing": ctrl-alt-o
"ai_assistant_panel:focus_terminal_input": none
"editor_view:select_all": ctrl-shift-A
"suggested_plan:edit": none
"code_diff_view:edit_requested_edit": none
"pane_group:add_left": ctrl-alt-left
"requested_command:refine": none
"workspace:toggle_command_palette": none
"code_diff_view:refine_requested_edit": none
"pane_group:navigate_prev": none
"pane_group:navigate_right": none
"pane_group:add_down": ctrl-alt-down
"workspace:shift_focus_right": none
"terminal:warpify_ssh_session": none
"terminal:ask_ai_assistant": none
